# Generated by Django 5.0.1 on 2024-02-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fileupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_from', models.CharField(max_length=255)),
                ('camera_number', models.IntegerField()),
                ('video_record_time', models.DateTimeField()),
                ('video_upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
